---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "nginx-1"
        image: "gcr.io/ringed-land-354108/apache-task3:prod"
        ports:
            - name: web
              containerPort: 80
              protocol: TCP
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-world-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "hello-world"
  type: "LoadBalancer"
  loadBalancerIP: ""
